### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lvivua032** [guialbuquerque5/binance-triangular-arbitrage-scan#1]
Traceback (most recent call last):
  File "bot.py", line 90, in <module>
    test(1)
  File "bot.py", line 79, in test
    g.att_prices(prices)
  File "C:\Users\Administrator\Desktop\binance-triangular-arbitrage-scan-master\graph.py", line 73, in att_prices
    self.update_matrix(str(price['symbol']),Decimal(str(price['askPrice'])),Decimal(str(price['bidPrice'])))
  File "C:\Users\Administrator\Desktop\binance-triangular-arbitrage-scan-master\graph.py", line 81, in update_matrix
    self.matrix[j][i] = 1/ask
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]

**Comment by nikos69** [comment]
got the same error too.
